name: GitHub Action 

on:
  push:
    branches: [master]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazw na repozytorium
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            jakubartlomiej/zad2:ghaction
            
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'     

      - name: Generate deployment package
        run: zip -r deploy.zip docker-compose.yml     
            
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: my-test-app
          environment_name: Mytestapp-env
          existing_bucket_name: elasticbeanstalk-us-east-1-048842524041
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip      
